version: 2.6.0.{build}
branches:
    only:
        - master

skip_tags: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: rYG0uD7eOutfMDvCi7Fe/W855aWp3b3/onQnk06bxp7EEKsYYdji5yD1euE8M37L

init:
    - cmd: git config --global core.autocrlf true

# Environment
image: Visual Studio 2017
clone_depth: 1

install:
    - git submodule update --init --recursive
    - nuget install OpenCover -OutputDirectory src\Couchbase.Lite.TestCoverage\packages -Version 4.7.922
    - nuget install xunit.runner.console -OutputDirectory src\Couchbase.Lite.TestCoverage\packages -Version 2.3.1
    
build_script:
    # Fail fast if C# is broken
    - cmd: msbuild /t:Restore src/Couchbase.Lite/Couchbase.Lite.csproj /p:Configuration=Debug_Coverage
    - cmd: msbuild src/Couchbase.Lite/Couchbase.Lite.csproj /p:JUST_CSHARP=1 /p:Configuration=Debug_Coverage
    # x86 is unused
    - ps: |
        New-Item -Type Directory vendor/couchbase-lite-core/build_cmake/x86/RelWithDebInfo
        Push-Location vendor/couchbase-lite-core/build_cmake/x86/RelWithDebInfo
        New-Item -Type File LiteCore.dll
        New-Item -Type File LiteCore.pdb
        Pop-Location

        New-Item -Type Directory vendor/couchbase-lite-core/build_cmake/x64
        Push-Location vendor/couchbase-lite-core/build_cmake/x64
        cmake -G "Visual Studio 14 2015 Win64" ..\..
        cmake --build . --target LiteCore --config RelWithDebInfo
        Pop-Location
    - cmd: msbuild /t:Restore src/Couchbase.Lite.TestCoverage/Couchbase.Lite.TestCoverage.csproj
    - cmd: msbuild src/Couchbase.Lite.TestCoverage/Couchbase.Lite.TestCoverage.sln

test_script:
    - ps: dotnet tool install coveralls.net --tool-path src\Couchbase.Lite.TestCoverage\coveralls
    - ps: Push-Location src\Couchbase.Lite.TestCoverage\bin\Debug\netcoreapp2.0; & ..\..\..\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -returntargetcode -register:user -target:dotnet.exe "-targetargs:""..\..\..\packages\xunit.runner.console.2.3.1\tools\netcoreapp2.0\xunit.console.dll"" "".\Couchbase.Lite.TestCoverage.dll"" -noshadow -appveyor"  -oldStyle -output:opencoverCoverage.xml -filter:"+[Couchbase.Lite]* -[Couchbase.Lite]LiteCore.Interop.*" -excludebyattribute:"*.ExcludeFromCodeCoverageAttribute" 2> $null
    - ps: |
        if (-not (Test-Path env:APPVEYOR_PULL_REQUEST_NUMBER)) {
            & "src\Couchbase.Lite.TestCoverage\coveralls\csmacnz.coveralls.exe" --opencover -i "src\Couchbase.Lite.TestCoverage\bin\Debug\netcoreapp2.0\opencoverCoverage.xml"
        }